Added key-pair correction

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,14 +30,15 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-southeast-1
 
-    - name: Check if Key Pair Exists
+    - name: Check if Key Pair Exists in AWS
       id: check_keypair
       run: |
-        aws ec2 describe-key-pairs --key-name my-key || echo "Key pair does not exist."
+        aws ec2 describe-key-pairs --key-name my-key > /dev/null 2>&1 || echo "notfound"
 
-    - name: Create Key Pair
-      if: steps.check_keypair.outputs.exists == ''
+    - name: Create Key Pair if Not Exists
+      if: steps.check_keypair.outputs.result == 'notfound'
       run: |
+        echo "Key pair not found, creating it..."
         aws ec2 create-key-pair --key-name my-key --query 'KeyMaterial' --output text > my-key.pem
         chmod 400 my-key.pem
 
@@ -53,3 +54,4 @@ jobs:
     - name: Run Pulumi stack
       run: |
         pulumi up --yes
+
